// practica2/vue/src/components/Main/Products/Products.vue
<script setup>
import { watch } from 'vue';
import { storeToRefs } from 'pinia';
import { useDataStore } from '../../../stores/products';
import ProductCard from './ProductCard.vue';

const dataStore = useDataStore();
const { filteredProducts } = storeToRefs(dataStore);

</script>

<template>
  <div class="flex flex-col w-full justify-center align-middle items-center content-center flex-wrap">
    <div class="flex flex-col w-full items-center" v-for="(product, index) in filteredProducts" :key="product.id">
      <ProductCard :product="product" />
      <hr v-if="index < filteredProducts.length - 1" class="w-10/12 my-4">
    </div>
  </div>
</template>

// practica2/react/src/components/Products/index.jsx
import React, { useEffect } from "react";
import { useDataStore } from "../../store/data";
import { ProductCard } from "./ProductCard";
export const Products = () => {
  const products = useDataStore((state) => state.products);
  const categories = useDataStore((state) => state.categories);
  const enabledCategories = categories
    .filter((category) => category.enabled)
    .map((category) => category.id);
  const filteredProducts = products.filter((product) =>
    enabledCategories.includes(product.categoryId)
  );

  return (
    <>
      <div className="flex flex-col w-full justify-center align-middle items-center content-center flex-wrap">
        {filteredProducts.map((product, index) => (
          <React.Fragment key={product.id}>
            <ProductCard product={product} />
            {index < filteredProducts.length - 1 && (
              <hr className="w-10/12 my-4" />
            )}
          </React.Fragment>
        ))}
      </div>
    </>
  );
};
