// practica2/vue/src/components/Modal/Modal.vue
<script setup>
import { defineProps } from 'vue';
import { Icon } from '@iconify/vue';

defineProps({
  show: {
    type: Boolean,
    required: true,
  },
});
</script>

<template>
  <div v-if="show" class="z-50 fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
    <div class="bg-white p-8 w-4/12 rounded-lg">
      <div class="flex flex-row w-full justify-end">
        <Icon icon="mdi:close-circle-outline" class="text-black cursor-pointer w-6 h-6" @click="$emit('close')" />
      </div>
      <slot @close="$emit('close')"></slot>
    </div>
  </div>
</template>

// practica2/react/src/components/Modal/index.jsx
import React, { useEffect, useState } from "react";
import { Icon } from "@iconify/react";
import { useSharedStore } from "../../store/shared";
import { LoginModal } from "./LoginModal";

export const Modal = () => {
  const openModal = useSharedStore((state) => state.openModal);
  const modalType = useSharedStore((state) => state.modalType);
  const setOpenModal = useSharedStore((state) => state.setOpenModal);
  const setModalType = useSharedStore((state) => state.setModalType);

  const closeModal = () => {
    setOpenModal(false);
    setModalType(null);
  };
  const [Child, setChild] = useState(null);

  useEffect(() => {
    if (!openModal || !modalType) return;
    if (modalType === "login") {
      setChild(() => LoginModal);
    }
  }, [openModal, modalType]);

  if (!openModal || !modalType) return null;

  return (
    <div className="z-50 fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
      <div className="bg-white p-8 w-4/12 rounded-lg">
        <div className="flex flex-row w-full justify-end">
          <Icon
            icon="mdi:close-circle-outline"
            className="text-black cursor-pointer w-6 h-6"
            onClick={() => closeModal()}
          />
        </div>
        {Child && <Child />}
      </div>
    </div>
  );
};
