// practica2/react/src/components/Categories/index.jsx
import React from "react";
import { useDataStore } from "../../store/data";
import { Category } from "./Category";

export const Categories = () => {
  const categories = useDataStore((state) => state.categories);

  return (
    <>
      <div className="flex flex-row w-full justify-center content-center">
        {categories.map((category) => (
          <React.Fragment key={category.id}>
            <Category category={category} />
          </React.Fragment>
        ))}
      </div>
    </>
  );
};

// practica2/vue/src/components/Main/Categories/Categories.vue
<script setup>
import { useDataStore } from '../../../stores/products';
import Category from './Category.vue';

const dataStore = useDataStore();
const { allCategories } = dataStore;

</script>

<template>
  <div class="flex flex-row w-full justify-center content-center">
    <div v-for="category in allCategories">
      <Category :category="category" />
    </div>

  </div>
</template>
